### ISSUE TITLE
champ package possible on noetic, or ros2 ?

### ISSUE THREAD

**Issue by elpimous** [chvmp/champ#66]
Hello,
Do you think I could convert your default walk package from python2 to python3 ?

Will i just have to convert your python2 files ?

I just need, for now the walk only.

Thanks, 
Have a nice day

**Comment by elpimous** [comment]
Hey, called the py file as py3,
Some ros py3 packages, 
And Success.

**Comment by lubitz99** [comment]
@elpimous Would you be able to let me know how you were able to update the code for ROS Noetic. I am struggling to make the workspace with python3.

**Comment by wmmc88** [comment]
Anyone have any success running this on ROS2?

**Comment by jediofgever** [comment]
Hi,
I have spent time porting a good chunk of champ code to ROS2 [here](https://github.com/jediofgever/quadruped_ros2),
There is an issue that I don't understand and I would be happy to collaborate with anyone interested running champ in ROS2. 

I suspect the issue is with controller, the robot keps wobbling in Gazebo as in below;

https://user-images.githubusercontent.com/18460336/168811789-5f4e9ae6-2734-401d-b22a-0e3851b7d3c4.mp4

**Comment by sskorol** [comment]
@jediofgever have you figured out your issue?
@grassjelly do you plan to create an official port for ROS2?

**Comment by grassjelly** [comment]
@sskorol you can checkout the ROS2 branch https://github.com/chvmp/champ/pull/86
