### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by DPR00** [chvmp/champ#72]
Hi there,

I followed the installation instructions given in the README file, but when I ran the "catkin_make" command I found these series of errors. 
![image](https://user-images.githubusercontent.com/69125793/137512116-fd5ea607-25d7-4e4c-9883-31832151eb04.png)

I've already done [this](https://github.com/chvmp/champ/issues/11#issuecomment-688642474), but It's still not working. I am running on ROS Melodic (Ubuntu 18.04) and I'm relatively new on ROS.

**Comment by Joyuan-sys** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; Thank you for your reply.I have solved this problem. The reason is that your protoubf
package does not match your ubuntu system. You should install it properly. Now I do my simulation in gazebo, but it can not walk. it is too tough ,hhh!





---Original---
From: "Diego ***@***.***&gt;
Date: Tue, Oct 19, 2021 00:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chvmp/champ] catkin_make error (#72)




 
Hi, I couldn't find a solution for that specific problem. I think it has a conflict with other packages that I have within my workspace. The reason is because, by curiosity, I decided to run the package on an external platform (ros development studio with ros melodic), and it ran without any issues. So, I decided to create a new workspace in my own computer (ubuntu 18.04), then followed the installation instructions again and it worked perfectly. I am testing now the launch files and everything is going fine until now.
 
PS: I'm not pretty sure if this is a conflict with other packages or another problem, so if you find the problem, please let me know.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elpimous** [comment]
hello @DPR00 ,  I have same problem and can't correct it .
Could you explain me what you did ?
Thanks friend

**Comment by DPR00** [comment]
Hi there @elpimous! 
I did not "fixed", but I was able to install it it by creating a new ROS workspace (ROS Melodic) and then followed the installation steps.
